DROP SCHEMA IF EXISTS typefast;
CREATE SCHEMA typefast COLLATE ascii_general_ci;
USE typefast;


CREATE TABLE Category
(
	idCat		INTEGER NOT NULL AUTO_INCREMENT,
	name		VARCHAR(50) NULL,
	PRIMARY KEY (idCat)
) ENGINE=InnoDB;

CREATE TABLE Text
(
	idTex		INTEGER NOT NULL AUTO_INCREMENT,
	content		VARCHAR(5000) NULL,
	idCat		INTEGER NOT NULL,
	approved	BOOLEAN NULL,
	PRIMARY KEY (idTex)
) ENGINE=InnoDB;

CREATE TABLE Daily
(
	idDai		INTEGER NOT NULL AUTO_INCREMENT,
	idTex		INTEGER NOT NULL,
	startTime	INTEGER NULL,
	PRIMARY KEY (idDai)
) ENGINE=InnoDB;

CREATE TABLE Person
(
	idPer		INTEGER NOT NULL AUTO_INCREMENT,
	username	VARCHAR(50) NULL,
	password	VARCHAR(256) NULL,
	op			INTEGER NULL,
	gold		INTEGER NULL,
	silver		INTEGER NULL,
	bronze		INTEGER NULL,
	blReason	VARCHAR(1000) NULL,
	blUntil		INTEGER NULL,
	
	PRIMARY KEY (idPer)
) ENGINE=InnoDB;

CREATE TABLE Score
(
	idSco		INTEGER NOT NULL AUTO_INCREMENT,
	idPer		INTEGER NOT NULL,
	idTex		INTEGER NOT NULL,
	datePlayed	DATE NULL,
	time		DOUBLE NULL,
	accuracy	DOUBLE NULL,
	PRIMARY KEY (idSco)
) ENGINE=InnoDB;

CREATE TABLE DailyScore
(
	idDSc		INTEGER NOT NULL AUTO_INCREMENT,
	idSco		INTEGER NOT NULL,
	PRIMARY KEY (idDSc)
) ENGINE=InnoDB;

CREATE TABLE Follows
(
	idFer		INTEGER NOT NULL,
	idFed		INTEGER NOT NULL,
	PRIMARY KEY (idFer, idFed)
) ENGINE=InnoDB;



ALTER TABLE Text
ADD CONSTRAINT R_2 FOREIGN KEY (idCat) REFERENCES Category (idCat);

ALTER TABLE Daily
ADD CONSTRAINT R_3 FOREIGN KEY (idTex) REFERENCES Text (idTex);

ALTER TABLE Score
ADD CONSTRAINT R_4 FOREIGN KEY (idPer) REFERENCES Person (idPer);

ALTER TABLE Score
ADD CONSTRAINT R_5 FOREIGN KEY (idTex) REFERENCES Text (idTex);

ALTER TABLE DailyScore
ADD CONSTRAINT R_6 FOREIGN KEY (idSco) REFERENCES Score (idSco);

ALTER TABLE Follows
ADD CONSTRAINT R_7 FOREIGN KEY (idFer) REFERENCES Person (idPer);

ALTER TABLE Follows
ADD CONSTRAINT R_8 FOREIGN KEY (idFed) REFERENCES Person (idPer);